/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminBlogsIdRouteImport } from './routes/admin.blogs.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogsRoute,
} as any)
const AdminBlogsIdRoute = AdminBlogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/blogs': typeof AdminBlogsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/terms'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin'
    | '/services'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin/blogs'
    | '/admin/login'
    | '/admin/messages'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/services/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
    '/admin/blogs/$id': {
      id: '/admin/blogs/$id'
      path: '/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminBlogsIdRouteImport
      parentRoute: typeof AdminBlogsRoute
    }
  }
}

interface AdminBlogsRouteChildren {
  AdminBlogsIdRoute: typeof AdminBlogsIdRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
}

const AdminBlogsRouteChildren: AdminBlogsRouteChildren = {
  AdminBlogsIdRoute: AdminBlogsIdRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
}

const AdminBlogsRouteWithChildren = AdminBlogsRoute._addFileChildren(
  AdminBlogsRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogsRoute: typeof AdminBlogsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogsRoute: AdminBlogsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
